version: '3.9'

services:
  db:
    image: postgres:16
    container_name: finance-db
    restart: always
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - /mnt/dados/finance-app2/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d finance"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./apps/api
    container_name: finance-api
    restart: always
    env_file: ./apps/api/.env
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

  web:
    build: ./apps/web
    container_name: finance-web
    restart: always
    env_file: ./apps/web/.env
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  pgdata:
