backend:
    image: node:18-alpine
    container_name: finance-app-backend
    restart: unless-stopped
    working_dir: /usr/src/app
  
    command: ["node", "src/server.js"]
    
    volumes:
      - /mnt/dados/finance-app/finance-app:/usr/src/app
    ports:
      - "3333:3333"
    environment:
      - DATABASE_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_NAME=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3333/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
