version: '3.8'

services:
  #--- Serviço do Back-end (API) ---
  backend:
    image: node:18-alpine
    # AJUSTE: Nome do contêiner padronizado.
    container_name: finance-app-backend
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      # AJUSTE E PONTO CRÍTICO:
      # Este caminho agora assume que, no seu servidor TrueNAS, você terá o
      # arquivo docker-compose.yml e, AO LADO DELE, uma pasta chamada 'finance-app'
      # que contém todo o seu código-fonte (package.json, src/, etc.).
      - ./finance-app:/usr/src/app
    ports:
      - "3333:3333"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=${POSTEGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_NAME=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db

  #--- Serviço do Banco de Dados (PostgreSQL) ---
  db:
    image: postgres:15-alpine
    # AJUSTE: Nome do contêiner padronizado.
    container_name: finance-app-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      # Caminho final e correto, conforme definimos.
      - /mnt/dados/finance-app/postgres-data:/var/lib/postgresql/data
