version: '3.8'

services:
  backend:
    image: node:18-alpine
    container_name: finance-app-backend
    restart: unless-stopped
    working_dir: /usr/src/app
    tty: true
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumes:
      # Caminho direto e absoluto para a pasta com o código que clonamos.
      - /mnt/dados/finance-app/finance-app:/usr/src/app
    ports:
      - "3333:3333"
    environment:
      - DATABASE_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_NAME=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: finance-app-postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /mnt/dados/finance-app/postgres-data:/var/lib/postgresql/data
